-- ESX items (oxmysql example). Run once, or add through your item SQL workflow.
-- If you use ox_inventory on ESX, use ox_inventory_items.lua instead.

INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
    ('black_blue_crown', 'Black Blue Crown', 1, 0, 1),
    ('black_cyan_crown', 'Black Cyan Crown', 1, 0, 1),
    ('black_gold_crown', 'Black Gold Crown', 1, 0, 1),
    ('black_green_crown', 'Black Green Crown', 1, 0, 1),
    ('black_pink_crown', 'Black Pink Crown', 1, 0, 1),
    ('black_purple_crown', 'Black Purple Crown', 1, 0, 1),
    ('black_red_crown', 'Black Red Crown', 1, 0, 1),
    ('black_white_crown', 'Black White Crown', 1, 0, 1),
    ('black_yellow_crown', 'Black Yellow Crown', 1, 0, 1),
    ('gold_blue_crown', 'Gold Blue Crown', 1, 0, 1),
    ('gold_cyan_crown', 'Gold Cyan Crown', 1, 0, 1),
    ('gold_green_crown', 'Gold Green Crown', 1, 0, 1),
    ('gold_pink_crown', 'Gold Pink Crown', 1, 0, 1),
    ('gold_purple_crown', 'Gold Purple Crown', 1, 0, 1),
    ('gold_red_crown', 'Gold Red Crown', 1, 0, 1),
    ('gold_white_crown', 'Gold White Crown', 1, 0, 1),
    ('silver_blue_crown', 'Silver Blue Crown', 1, 0, 1),
    ('silver_cyan_crown', 'Silver Cyan Crown', 1, 0, 1),
    ('silver_gold_crown', 'Silver Gold Crown', 1, 0, 1),
    ('silver_green_crown', 'Silver Green Crown', 1, 0, 1),
    ('silver_pink_crown', 'Silver Pink Crown', 1, 0, 1),
    ('silver_purple_crown', 'Silver Purple Crown', 1, 0, 1),
    ('silver_red_crown', 'Silver Red Crown', 1, 0, 1),
    ('silver_yellow_crown', 'Silver Yellow Crown', 1, 0, 1),
    ('halo_black', 'Halo Black', 1, 0, 1),
    ('halo_blue', 'Halo Blue', 1, 0, 1),
    ('halo_gold', 'Halo Gold', 1, 0, 1),
    ('halo_green', 'Halo Green', 1, 0, 1),
    ('halo_orange', 'Halo Orange', 1, 0, 1),
    ('halo_pink', 'Halo Pink', 1, 0, 1),
    ('halo_purple', 'Halo Purple', 1, 0, 1),
    ('halo_red', 'Halo Red', 1, 0, 1),
    ('halo_white', 'Halo White', 1, 0, 1),
    ('angelwings_black', 'Black Angel Wings', 1, 0, 1),
    ('angelwings_blue', 'Blue Angel Wings', 1, 0, 1),
    ('angelwings_green', 'Green Angel Wings', 1, 0, 1),
    ('angelwings_grey', 'Grey Angel Wings', 1, 0, 1),
    ('angelwings_orange', 'Orange Angel Wings', 1, 0, 1),
    ('angelwings_pink', 'Pink Angel Wings', 1, 0, 1),
    ('angelwings_purple', 'Purple Angel Wings', 1, 0, 1),
    ('angelwings_red', 'Red Angel Wings', 1, 0, 1),
    ('angelwings_tan', 'Tan Angel Wings', 1, 0, 1),
    ('angelwings_white', 'White Angel Wings', 1, 0, 1),
    ('angelwings_yellow', 'Yellow Angel Wings', 1, 0, 1),
    ('bluemorpho_aura', 'Blue Morpho Aura', 1, 0, 1),
    ('bluewings', 'Blue Wings', 1, 0, 1),
    ('greenmorpho_aura', 'Green Morpho Aura', 1, 0, 1),
    ('greenwings', 'Green Wings', 1, 0, 1),
    ('lavendermorpho_aura', 'Lavender Morpho Aura', 1, 0, 1),
    ('monochromemorpho_aura', 'Monochrome Morpho Aura', 1, 0, 1),
    ('orangewings', 'Orange Wings', 1, 0, 1),
    ('pinkmorpho_aura', 'Pink Morpho Aura', 1, 0, 1),
    ('pinkwings', 'Pink Wings', 1, 0, 1),
    ('purplewings', 'Purple Wings', 1, 0, 1),
    ('redwings', 'Red Wings', 1, 0, 1),
    ('whitewings', 'White Wings', 1, 0, 1),
    ('yellowwings', 'Yellow Wings', 1, 0, 1),
    ('alientoy', 'Alien Toy', 1, 0, 1),
    ('armored_cat', 'Armored Cat', 1, 0, 1),
    ('autumndragon_toy', 'Autumn Dragon Toy', 1, 0, 1),
    ('avocadotoy', 'Avocado Toy', 1, 0, 1),
    ('babydragon2_by_joao', 'Baby Dragon 2', 1, 0, 1),
    ('babydragon3_by_joao', 'Baby Dragon 3', 1, 0, 1),
    ('babydragon4_by_joao', 'Baby Dragon 4', 1, 0, 1),
    ('babydragon5_by_joao', 'Baby Dragon 5', 1, 0, 1),
    ('babydragon6_by_joao', 'Baby Dragon 6', 1, 0, 1),
    ('babydragon_by_joao', 'Baby Dragon', 1, 0, 1),
    ('banditboa_toy', 'Bandit Boa Toy', 1, 0, 1),
    ('bearballoontoy', 'Bear Balloon Toy', 1, 0, 1),
    ('black_ghost', 'Black Ghost', 1, 0, 1),
    ('blackcattoy', 'Black Cat Toy', 1, 0, 1),
    ('blackrabbittoy', 'Black Rabbit Toy', 1, 0, 1),
    ('blackshibatoy', 'Black Shiba Toy', 1, 0, 1),
    ('blossom', 'Blossom', 1, 0, 1),
    ('bluefoxtoy', 'Blue Fox Toy', 1, 0, 1),
    ('bluemushroomtoy', 'Blue Mushroom Toy', 1, 0, 1),
    ('brownchickentoy', 'Brown Chicken Toy', 1, 0, 1),
    ('brownowltoy', 'Brown Owl Toy', 1, 0, 1),
    ('brownrabbittoy', 'Brown Rabbit Toy', 1, 0, 1),
    ('bubbles', 'Bubbles', 1, 0, 1),
    ('bumblebeetoy', 'Bumblebee Toy', 1, 0, 1),
    ('buttercup', 'Buttercup', 1, 0, 1),
    ('cactustoy', 'Cactus Toy', 1, 0, 1),
    ('clovercat_toy', 'Clover Cat Toy', 1, 0, 1),
    ('coraldragon_toy', 'Coral Dragon Toy', 1, 0, 1),
    ('cuteghost_toy', 'Cute Ghost Toy', 1, 0, 1),
    ('dancingduck_toy', 'Dancing Duck Toy', 1, 0, 1),
    ('darkphoenix_toy', 'Dark Phoenix Toy', 1, 0, 1),
    ('dino', 'Dino', 1, 0, 1),
    ('dino_student', 'Student Dino', 1, 0, 1),
    ('edgemonkey_toy', 'Edge Monkey', 1, 0, 1),
    ('fiestadoggo_toy', 'Fiesta Doggo', 1, 0, 1),
    ('firekitsune_toy', 'Fire Kitsune', 1, 0, 1),
    ('fox', 'Fox', 1, 0, 1),
    ('frogtoy', 'Frog Toy', 1, 0, 1),
    ('gerbiltoy', 'Gerbil Toy', 1, 0, 1),
    ('ghosttoy', 'Ghost Toy', 1, 0, 1),
    ('glen_toy', 'Glen', 1, 0, 1),
    ('graffitibear_toy', 'Graffiti Bear Toy', 1, 0, 1),
    ('greenfrogtoy', 'Green Frog Toy', 1, 0, 1),
    ('heartbreakimp_toy', 'Heartbreak Imp', 1, 0, 1),
    ('holidaybeartoy', 'Holiday Bear Toy', 1, 0, 1),
    ('holidaycockatieltoy', 'Holiday Cockatiel', 1, 0, 1),
    ('hollow_knight', 'Hollow Knight', 1, 0, 1),
    ('icepup_toy', 'Ice Pup Toy', 1, 0, 1),
    ('jellycloud_toy', 'Jelly Cloud Toy', 1, 0, 1),
    ('knight_cat', 'Knight Cat', 1, 0, 1),
    ('labtoy', 'Lab Toy', 1, 0, 1),
    ('magicdovetoy', 'Magic Dove', 1, 0, 1),
    ('mickey_mouse', 'Mickey Mouse', 1, 0, 1),
    ('mintaxolotltoy', 'Mint Axolotl Toy', 1, 0, 1),
    ('monkey_punk', 'Monkey Punk', 1, 0, 1),
    ('monky', 'Monky', 1, 0, 1),
    ('noctibat_animation', 'Noctibat', 1, 0, 1),
    ('orangecattoy', 'Orange Cat Toy', 1, 0, 1),
    ('owltoy', 'Owl Toy', 1, 0, 1),
    ('periwinkleaxolotltoy', 'Periwinkle Axolotl', 1, 0, 1),
    ('pig_angel', 'Pig Angel', 1, 0, 1),
    ('pinkaxolotltoy', 'Pink Axolotl Toy', 1, 0, 1),
    ('pinkfoxtoy', 'Pink Fox Toy', 1, 0, 1),
    ('pinkfrogtoy', 'Pink Frog Toy', 1, 0, 1),
    ('pinkkoalatoy', 'Pink Koala Toy', 1, 0, 1),
    ('pinkpandatoy', 'Pink Panda Toy', 1, 0, 1),
    ('pinkrabbittoy', 'Pink Rabbit Toy', 1, 0, 1),
    ('purplefoxtoy', 'Purple Fox Toy', 1, 0, 1),
    ('purplemushroomtoy', 'Purple Mushroom Toy', 1, 0, 1),
    ('questing_mouse', 'Questing Mouse', 1, 0, 1),
    ('raccoontoy', 'Raccoon Toy', 1, 0, 1),
    ('rainbowaxolotltoy', 'Rainbow Axolotl Toy', 1, 0, 1),
    ('rainbowtoy', 'Rainbow Toy', 1, 0, 1),
    ('raventoy', 'Raven Toy', 1, 0, 1),
    ('raveshibatoy', 'Rave Shiba Toy', 1, 0, 1),
    ('reapertoy', 'Reaper Toy', 1, 0, 1),
    ('redfoxtoy', 'Red Fox Toy', 1, 0, 1),
    ('redmushroomtoy', 'Red Mushroom Toy', 1, 0, 1),
    ('redpandatoy', 'Red Panda Toy', 1, 0, 1),
    ('rosemoth_toy', 'Rose Moth Toy', 1, 0, 1),
    ('sagerabbittoy', 'Sage Rabbit Toy', 1, 0, 1),
    ('sakurashibatoy', 'Sakura Shiba Toy', 1, 0, 1),
    ('scarecrow_toy', 'Scarecrow Toy', 1, 0, 1),
    ('shark_boi', 'Shark Boi', 1, 0, 1),
    ('shibatoy', 'Shiba Toy', 1, 0, 1),
    ('shoulderguardianstoy', 'Shoulder Guardians', 1, 0, 1),
    ('skelebuddyred', 'Red Skelebuddy', 1, 0, 1),
    ('skeletonunicorntoy', 'Skeleton Unicorn Toy', 1, 0, 1),
    ('snowleopard_toy', 'Snow Leopard Toy', 1, 0, 1),
    ('snowmantoy', 'Snowman Toy', 1, 0, 1),
    ('springbunny_toy', 'Spring Bunny Toy', 1, 0, 1),
    ('strawberrykit_toy', 'Strawberry Kit Toy', 1, 0, 1),
    ('sunflowerpanda_toy', 'Sunflower Panda Toy', 1, 0, 1),
    ('tacocattoy', 'Taco Cat Toy', 1, 0, 1),
    ('turkey_toy', 'Turkey Toy', 1, 0, 1),
    ('unicorntoy', 'Unicorn Toy', 1, 0, 1),
    ('voodoodoll_toy', 'Voodoo Doll Toy', 1, 0, 1),
    ('white_ghost', 'White Ghost', 1, 0, 1),
    ('whitecattoy', 'White Cat Toy', 1, 0, 1),
    ('whitechickentoy', 'White Chicken Toy', 1, 0, 1),
    ('whiterabbittoy', 'White Rabbit Toy', 1, 0, 1),
    ('winterfoxtoy', 'Winter Fox Toy', 1, 0, 1),
    ('yellowaxolotltoy', 'Yellow Axolotl Toy', 1, 0, 1),
    ('abelha_plushie_shop', 'Bee Plushie', 1, 0, 1),
    ('angelalien_plushie', 'Angel Alien Plushie', 1, 0, 1),
    ('angelduck_plushie', 'Angel Duck Plushie', 1, 0, 1),
    ('banana_01_plushie_shop', 'Banana 01 Plushie', 1, 0, 1),
    ('bear2_01_plushie_shop', 'Bear2 01 Plushie', 1, 0, 1),
    ('bear3_01_plushie_shop', 'Bear3 01 Plushie', 1, 0, 1),
    ('bear4_01_plushie_shop', 'Bear4 01 Plushie', 1, 0, 1),
    ('bear5_01_plushie_shop', 'Bear5 01 Plushie', 1, 0, 1),
    ('bear6_01_plushie_shop', 'Bear6 01 Plushie', 1, 0, 1),
    ('bear7_01_plushie_shop', 'Bear7 01 Plushie', 1, 0, 1),
    ('bear8_01_plushie_shop', 'Bear8 01 Plushie', 1, 0, 1),
    ('bear_01_plushie_shop', 'Bear 01 Plushie', 1, 0, 1),
    ('bear_02_plushie_shop', 'Bear 02 Plushie', 1, 0, 1),
    ('bear_03_plushie_shop', 'Bear 03 Plushie', 1, 0, 1),
    ('bear_04_plushie_shop', 'Bear 04 Plushie', 1, 0, 1),
    ('bear_05_plushie_shop', 'Bear 05 Plushie', 1, 0, 1),
    ('bear_06_plushie_shop', 'Bear 06 Plushie', 1, 0, 1),
    ('bunalien_plushie', 'Bun Alien Plushie', 1, 0, 1),
    ('bunny1_01_plushie_shop', 'Bunny1 01 Plushie', 1, 0, 1),
    ('bunny1_02_plushie_shop', 'Bunny1 02 Plushie', 1, 0, 1),
    ('bunny1_03_plushie_shop', 'Bunny1 03 Plushie', 1, 0, 1),
    ('bunny1_04_plushie_shop', 'Bunny1 04 Plushie', 1, 0, 1),
    ('bunny1_05_plushie_shop', 'Bunny1 05 Plushie', 1, 0, 1),
    ('bunny1_06_plushie_shop', 'Bunny1 06 Plushie', 1, 0, 1),
    ('bunny1_07_plushie_shop', 'Bunny1 07 Plushie', 1, 0, 1),
    ('bunny2_01_plushie_shop', 'Bunny2 01 Plushie', 1, 0, 1),
    ('bunny2_02_plushie_shop', 'Bunny2 02 Plushie', 1, 0, 1),
    ('bunny2_03_plushie_shop', 'Bunny2 03 Plushie', 1, 0, 1),
    ('bunny2_04_plushie_shop', 'Bunny2 04 Plushie', 1, 0, 1),
    ('bunny2_05_plushie_shop', 'Bunny2 05 Plushie', 1, 0, 1),
    ('bunny2_06_plushie_shop', 'Bunny2 06 Plushie', 1, 0, 1),
    ('bunny2_07_plushie_shop', 'Bunny2 07 Plushie', 1, 0, 1),
    ('bunny2_08_plushie_shop', 'Bunny2 08 Plushie', 1, 0, 1),
    ('bunny2_09_plushie_shop', 'Bunny2 09 Plushie', 1, 0, 1),
    ('bunny2_10_plushie_shop', 'Bunny2 10 Plushie', 1, 0, 1),
    ('bunny3_01_plushie_shop', 'Bunny3 01 Plushie', 1, 0, 1),
    ('bunny3_02_plushie_shop', 'Bunny3 02 Plushie', 1, 0, 1),
    ('bunny3_03_plushie_shop', 'Bunny3 03 Plushie', 1, 0, 1),
    ('bunny3_04_plushie_shop', 'Bunny3 04 Plushie', 1, 0, 1),
    ('bunny3_05_plushie_shop', 'Bunny3 05 Plushie', 1, 0, 1),
    ('bunny3_06_plushie_shop', 'Bunny3 06 Plushie', 1, 0, 1),
    ('bunny3_07_plushie_shop', 'Bunny3 07 Plushie', 1, 0, 1),
    ('bunny3_08_plushie_shop', 'Bunny3 08 Plushie', 1, 0, 1),
    ('bunny3_09_plushie_shop', 'Bunny3 09 Plushie', 1, 0, 1),
    ('bunny3_10_plushie_shop', 'Bunny3 10 Plushie', 1, 0, 1),
    ('bunny4_01_plushie_shop', 'Bunny4 01 Plushie', 1, 0, 1),
    ('bunny4_02_plushie_shop', 'Bunny4 02 Plushie', 1, 0, 1),
    ('bunny4_03_plushie_shop', 'Bunny4 03 Plushie', 1, 0, 1),
    ('bunny4_04_plushie_shop', 'Bunny4 04 Plushie', 1, 0, 1),
    ('bunny4_05_plushie_shop', 'Bunny4 05 Plushie', 1, 0, 1),
    ('bunny4_06_plushie_shop', 'Bunny4 06 Plushie', 1, 0, 1),
    ('bunny4_07_plushie_shop', 'Bunny4 07 Plushie', 1, 0, 1),
    ('bunny4_08_plushie_shop', 'Bunny4 08 Plushie', 1, 0, 1),
    ('capivara_plushie_shop', 'Capybara Plushie', 1, 0, 1),
    ('cat_01_plushie_shop', 'Cat 01 Plushie', 1, 0, 1),
    ('cat_02_plushie_shop', 'Cat 02 Plushie', 1, 0, 1),
    ('cat_03_plushie_shop', 'Cat 03 Plushie', 1, 0, 1),
    ('cat_04_plushie_shop', 'Cat 04 Plushie', 1, 0, 1),
    ('cat_05_plushie_shop', 'Cat 05 Plushie', 1, 0, 1),
    ('cat_06_plushie_shop', 'Cat 06 Plushie', 1, 0, 1),
    ('chococow_plushie', 'Choco Cow Plushie', 1, 0, 1),
    ('coelho2_plushie_shop', 'Coelho2 Plushie', 1, 0, 1),
    ('coelho_plushie_shop', 'Rabbit Plushie', 1, 0, 1),
    ('cosmicalien_plushie', 'Cosmic Alien Plushie', 1, 0, 1),
    ('devilduck_plushie', 'Devil Duck Plushie', 1, 0, 1),
    ('dinossauro_plushie_shop', 'Dinosaur Plushie', 1, 0, 1),
    ('dog_01_plushie_shop', 'Dog 01 Plushie', 1, 0, 1),
    ('duck_01_plushie_shop', 'Duck 01 Plushie', 1, 0, 1),
    ('duck_02_plushie_shop', 'Duck 02 Plushie', 1, 0, 1),
    ('duck_03_plushie_shop', 'Duck 03 Plushie', 1, 0, 1),
    ('duck_04_plushie_shop', 'Duck 04 Plushie', 1, 0, 1),
    ('duck_05_plushie_shop', 'Duck 05 Plushie', 1, 0, 1),
    ('duck_06_plushie_shop', 'Duck 06 Plushie', 1, 0, 1),
    ('foxwitch_01_plushie_shop', 'Fox Witch 01 Plushie', 1, 0, 1),
    ('foxwitch_02_plushie_shop', 'Fox Witch 02 Plushie', 1, 0, 1),
    ('foxwitch_03_plushie_shop', 'Fox Witch 03 Plushie', 1, 0, 1),
    ('foxwitch_04_plushie_shop', 'Fox Witch 04 Plushie', 1, 0, 1),
    ('foxwitch_05_plushie_shop', 'Fox Witch 05 Plushie', 1, 0, 1),
    ('foxwitch_06_plushie_shop', 'Fox Witch 06 Plushie', 1, 0, 1),
    ('foxwitch_07_plushie_shop', 'Fox Witch 07 Plushie', 1, 0, 1),
    ('foxwitch_08_plushie_shop', 'Fox Witch 08 Plushie', 1, 0, 1),
    ('foxwitch_09_plushie_shop', 'Fox Witch 09 Plushie', 1, 0, 1),
    ('foxwitch_10_plushie_shop', 'Fox Witch 10 Plushie', 1, 0, 1),
    ('foxwitch_11_plushie_shop', 'Fox Witch 11 Plushie', 1, 0, 1),
    ('frog2_01_plushie_shop', 'Frog2 01 Plushie', 1, 0, 1),
    ('frog2_02_plushie_shop', 'Frog2 02 Plushie', 1, 0, 1),
    ('frog2_03_plushie_shop', 'Frog2 03 Plushie', 1, 0, 1),
    ('frog2_04_plushie_shop', 'Frog2 04 Plushie', 1, 0, 1),
    ('frog2_05_plushie_shop', 'Frog2 05 Plushie', 1, 0, 1),
    ('frog2_06_plushie_shop', 'Frog2 06 Plushie', 1, 0, 1),
    ('frog2_07_plushie_shop', 'Frog2 07 Plushie', 1, 0, 1),
    ('frog_01_plushie_shop', 'Frog 01 Plushie', 1, 0, 1),
    ('galaxycow_plushie', 'Galaxy Cow Plushie', 1, 0, 1),
    ('gamerduck_plushie', 'Gamer Duck Plushie', 1, 0, 1),
    ('gardenerduck_plushie', 'Gardener Duck Plushie', 1, 0, 1),
    ('gato_01_plushie_shop', 'Cat 01 Plushie', 1, 0, 1),
    ('gato_02_plushie_shop', 'Cat 02 Plushie', 1, 0, 1),
    ('gato_03_plushie_shop', 'Cat 03 Plushie', 1, 0, 1),
    ('gato_04_plushie_shop', 'Cat 04 Plushie', 1, 0, 1),
    ('gato_05_plushie_shop', 'Cat 05 Plushie', 1, 0, 1),
    ('gato_06_plushie_shop', 'Cat 06 Plushie', 1, 0, 1),
    ('gato_07_plushie_shop', 'Cat 07 Plushie', 1, 0, 1),
    ('gato_08_plushie_shop', 'Cat 08 Plushie', 1, 0, 1),
    ('gothduck_plushie', 'Goth Duck Plushie', 1, 0, 1),
    ('greenalien_plushie', 'Green Alien Plushie', 1, 0, 1),
    ('highlandcow_plushie', 'Highland Cow Plushie', 1, 0, 1),
    ('jacare_plushie_shop', 'Alligator Plushie', 1, 0, 1),
    ('lavaalien_plushie', 'Lava Alien Plushie', 1, 0, 1),
    ('marsalien_plushie', 'Mars Alien Plushie', 1, 0, 1),
    ('matchacow_plushie', 'Matcha Cow Plushie', 1, 0, 1),
    ('monk_01_plushie_shop', 'Monkey 01 Plushie', 1, 0, 1),
    ('mouse2_01_plushie_shop', 'Mouse2 01 Plushie', 1, 0, 1),
    ('mouse2_02_plushie_shop', 'Mouse2 02 Plushie', 1, 0, 1),
    ('mouse2_03_plushie_shop', 'Mouse2 03 Plushie', 1, 0, 1),
    ('mouse2_04_plushie_shop', 'Mouse2 04 Plushie', 1, 0, 1),
    ('mouse2_05_plushie_shop', 'Mouse2 05 Plushie', 1, 0, 1),
    ('mouse2_06_plushie_shop', 'Mouse2 06 Plushie', 1, 0, 1),
    ('mouse3_01_plushie_shop', 'Mouse3 01 Plushie', 1, 0, 1),
    ('mouse3_02_plushie_shop', 'Mouse3 02 Plushie', 1, 0, 1),
    ('mouse3_03_plushie_shop', 'Mouse3 03 Plushie', 1, 0, 1),
    ('mouse3_04_plushie_shop', 'Mouse3 04 Plushie', 1, 0, 1),
    ('mouse3_05_plushie_shop', 'Mouse3 05 Plushie', 1, 0, 1),
    ('mouse3_06_plushie_shop', 'Mouse3 06 Plushie', 1, 0, 1),
    ('mouse3_07_plushie_shop', 'Mouse3 07 Plushie', 1, 0, 1),
    ('mouse3_08_plushie_shop', 'Mouse3 08 Plushie', 1, 0, 1),
    ('mouse_01_plushie_shop', 'Mouse 01 Plushie', 1, 0, 1),
    ('mouse_02_plushie_shop', 'Mouse 02 Plushie', 1, 0, 1),
    ('mouse_03_plushie_shop', 'Mouse 03 Plushie', 1, 0, 1),
    ('mouse_04_plushie_shop', 'Mouse 04 Plushie', 1, 0, 1),
    ('mouse_05_plushie_shop', 'Mouse 05 Plushie', 1, 0, 1),
    ('mouse_06_plushie_shop', 'Mouse 06 Plushie', 1, 0, 1),
    ('mushroom_01_plushie_shop', 'Mushroom 01 Plushie', 1, 0, 1),
    ('mushroom_02_plushie_shop', 'Mushroom 02 Plushie', 1, 0, 1),
    ('mushroom_03_plushie_shop', 'Mushroom 03 Plushie', 1, 0, 1),
    ('mushroom_04_plushie_shop', 'Mushroom 04 Plushie', 1, 0, 1),
    ('mushroom_05_plushie_shop', 'Mushroom 05 Plushie', 1, 0, 1),
    ('mushroom_06_plushie_shop', 'Mushroom 06 Plushie', 1, 0, 1),
    ('mushroom_07_plushie_shop', 'Mushroom 07 Plushie', 1, 0, 1),
    ('octoalien_plushie', 'Octo Alien Plushie', 1, 0, 1),
    ('panda_plushie_shop', 'Panda Plushie', 1, 0, 1),
    ('pinguimrosa_plushie_shop', 'Pink Penguin Plushie', 1, 0, 1),
    ('pit2_01_plushie_shop', 'Pit2 01 Plushie', 1, 0, 1),
    ('pit3_01_plushie_shop', 'Pit3 01 Plushie', 1, 0, 1),
    ('pit_01_plushie_shop', 'Pitbull 01 Plushie', 1, 0, 1),
    ('polvo_01_plushie_shop', 'Octopus 01 Plushie', 1, 0, 1),
    ('polvo_02_plushie_shop', 'Octopus 02 Plushie', 1, 0, 1),
    ('polvo_03_plushie_shop', 'Octopus 03 Plushie', 1, 0, 1),
    ('polvo_04_plushie_shop', 'Octopus 04 Plushie', 1, 0, 1),
    ('polvo_05_plushie_shop', 'Octopus 05 Plushie', 1, 0, 1),
    ('polvo_06_plushie_shop', 'Octopus 06 Plushie', 1, 0, 1),
    ('polvo_07_plushie_shop', 'Octopus 07 Plushie', 1, 0, 1),
    ('polvo_08_plushie_shop', 'Octopus 08 Plushie', 1, 0, 1),
    ('polvo_09_plushie_shop', 'Octopus 09 Plushie', 1, 0, 1),
    ('raincow_plushie', 'Rain Cow Plushie', 1, 0, 1),
    ('rinoceronte2_plushie_shop', 'Rinoceronte2 Plushie', 1, 0, 1),
    ('rinoceronte3_plushie_shop', 'Rinoceronte3 Plushie', 1, 0, 1),
    ('rinoceronte4_plushie_shop', 'Rinoceronte4 Plushie', 1, 0, 1),
    ('rinoceronte_plushie_shop', 'Rhino Plushie', 1, 0, 1),
    ('sakuracow_plushie', 'Sakura Cow Plushie', 1, 0, 1),
    ('sleepyduck_plushie', 'Sleepy Duck Plushie', 1, 0, 1),
    ('sunflowercow_plushie', 'Sunflower Cow Plushie', 1, 0, 1),
    ('thugduck_plushie', 'Thug Duck Plushie', 1, 0, 1),
    ('unicorn_01_plushie_shop', 'Unicorn 01 Plushie', 1, 0, 1),
    ('ursinhocarinhoso_01_plushie_shop', 'Care Bear 01 Plushie', 1, 0, 1),
    ('ursinhocarinhoso_02_plushie_shop', 'Care Bear 02 Plushie', 1, 0, 1),
    ('ursinhocarinhoso_03_plushie_shop', 'Care Bear 03 Plushie', 1, 0, 1),
    ('ursinhocarinhoso_04_plushie_shop', 'Care Bear 04 Plushie', 1, 0, 1),
    ('ursinhocarinhoso_05_plushie_shop', 'Care Bear 05 Plushie', 1, 0, 1),
    ('ursinhocarinhoso_06_plushie_shop', 'Care Bear 06 Plushie', 1, 0, 1),
    ('ursinhocarinhoso_07_plushie_shop', 'Care Bear 07 Plushie', 1, 0, 1),
    ('ursinhocarinhoso_08_plushie_shop', 'Care Bear 08 Plushie', 1, 0, 1),
    ('ursinhocarinhoso_09_plushie_shop', 'Care Bear 09 Plushie', 1, 0, 1),
    ('vaca_plushie_shop', 'Cow Plushie', 1, 0, 1),
    ('voidalien_plushie', 'Void Alien Plushie', 1, 0, 1);
